# mellanoxConfigDBCmdExecute
.1.3.6.1.4.1.33049.12.1.1.2.3:
  1: 'mellanoxConfigDBCmdExecuteBinarySwitchTo' # mellanoxConfigDBCmdExecuteBinarySwitchTo
  2: 'mellanoxConfigDBCmdExecuteTextApply' # mellanoxConfigDBCmdExecuteTextApply
  3: 'mellanoxConfigDBCmdExecuteTextApplyFailContinue' # mellanoxConfigDBCmdExecuteTextApplyFailContinue
  4: 'mellanoxConfigDBCmdExecuteBinaryUpload' # mellanoxConfigDBCmdExecuteBinaryUpload
  5: 'mellanoxConfigDBCmdExecuteTextUpload' # mellanoxConfigDBCmdExecuteTextUpload
  6: 'mellanoxConfigDBCmdExecuteConfigWrite' # mellanoxConfigDBCmdExecuteConfigWrite
  7: 'mellanoxConfigDBCmdExecuteBinaryDelete' # mellanoxConfigDBCmdExecuteBinaryDelete
  8: 'mellanoxConfigDBCmdExecuteTextDelete' # mellanoxConfigDBCmdExecuteTextDelete
