MELLANOX-CONFIG-DB-MIB::mellanoxConfigDBCmd:
  mib: MELLANOX-CONFIG-DB-MIB
  object: mellanoxConfigDBCmd
  discovery_attribute: mellanoxConfigDBCmdUri
  attributes:
    mellanoxConfigDBCmdUri:
      oid: .1.3.6.1.4.1.33049.12.1.1.2.1
      name: mellanox.ConfigDBCmdUri
      syntax: DisplayString
    mellanoxConfigDBCmdFilename:
      oid: .1.3.6.1.4.1.33049.12.1.1.2.2
      name: mellanox.ConfigDBCmdFilename
      syntax: DisplayString
    mellanoxConfigDBCmdExecute:
      oid: .1.3.6.1.4.1.33049.12.1.1.2.3
      name: mellanox.ConfigDBCmdExecute
      syntax: EnumInteger
    mellanoxConfigDBCmdStatus:
      oid: .1.3.6.1.4.1.33049.12.1.1.2.4
      name: mellanox.ConfigDBCmdStatus
      syntax: Integer32
      metric: gauge
    mellanoxConfigDBCmdStatusString:
      oid: .1.3.6.1.4.1.33049.12.1.1.2.5
      name: mellanox.ConfigDBCmdStatusString
      syntax: DisplayString
